### ISSUE TITLE
[Mod Info] Empty It! [Steam ID 1661072176] by Keallu

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#10]
### **Mod:**
Empty It! [Steam ID 1661072176] by Keallu

### **Other Information**
- **Additional info**: anything else you want to tell.

Compat report currently states:

```
 - This mod is now only needed for cemeteries. The Waste Transfer and Processing 
   facilities from the game cover the other functionalities from this mod. 
```

It's also useful for **snow dumps** on Snow biome maps (Snowfall DLC).

Note also that it doesn't affect **Waste Transfer Facility** - a feature many users have requested since Snowfall DLC. It's compat with Snowfall, but doesn't allow control over when waste transfer trucks are sent out.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
