### ISSUE TITLE
[Mod] No Abandonment [Steam ID  552309905] by T​​​P​​​B

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#11]
### **Mod:**
No Abandonment [Steam ID  552309905] by T​​​P​​​B

### **Stability:**
- **Broken**: Not?

Compat report states:

```
 - Unsubscribe! This mod is broken.
```

Is this mod actually broken? I've been using it and it seems to work - it prevents buildings becoming abandonned due to issues. However it won't "un-abandon" buildings which are already abandonned (which I suspect is why most users will consider it broken).

It's using old version of Harmony and maybe it might be better suggesting the alternative (Advanced Building Level Control mod) based on harmony issue, rather than treating No Abandonment as outright broken mod?

If No Abandonment mod does have serious issues, it would be useful to describe what they are IMO.

**Comment by Finwickle** [comment]
Here I just followed the large amount of users saying it doesn't work. I'll change it to UsersReportIssues with a note saying that it seems to work for some users, and a note about not working on existing abandoned buildings.
This will be updated in catalog 3.48.
