### ISSUE TITLE
[Mod Info] Train Converter [Steam ID  795514116] by BloodyPenguin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#12]
### **Mod:**
Train Converter [Steam ID  795514116] by BloodyPenguin

### **Stability:**
- **Minor issues**: it functions, but with some smaller issues (please elaborate below).
    * It's confirmed to work with current game version (Sunset Harbour at least).
    * If you subscribe too many train assets, the mods' options screen might break
    * Some users report issues with config file not being properly created

### **Statuses:**

- **Performance impact**: it functions, but lowers the game FPS, increases loading time, ...
    * Impairs performance of content manager - has huge options screen with many UI components, so causes lag each time a mod or asset is enabled/disabled/subscribed/unsubscribed
    * Reduces fps in game due to large options screen - the main FPS Booster mod can be used to tackle that issue (by disabling UI components which are not in active use)
- **Source code**: available at **URL**
    * https://github.com/bloodypenguin/Skylines-VehicleConverter

### **Other Information**

- **Required mods/DLC**: missing, or listed ones are not needed. Specificy which one.

Requires `Prefab Hook`: https://steamcommunity.com/workshop/filedetails/?id=530771650

Conversion of trains in to trams will require Snowfall DLC (the mod works fine without Snowfall; it won't show the tram options).

- **Additional info**: anything else you want to tell.

Most users probably don't require this mod, it's mainly used to convert very old train assets (which were designed to look like metros/trams) in to actual metros/trams. It's default conversions are [listed here](https://steamcommunity.com/workshop/filedetails/discussion/795514116/276237094327064093/). However, it can be used to convert _any_ train to a metro/tram either via its options screen or config file, should users wish to do so.

**Comment by Finwickle** [comment]
This will be added to catalog 3.50.
