### ISSUE TITLE
[Mod Info] Crash FM Radio Station (OLD) [Steam ID 2065332413] by johnyTahn

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#13]
### **Mod:**
Crash FM Radio Station (OLD) [Steam ID 2065332413] by johnyTahn

### **Stability:**
- **Stable**: it simply functions fine.

I use this; not had any problems.

### **Statuses:**
- **Deprecated**: users are discouraged to use this any longer; it won't be supported or updated.

Not acutally deprecated - author stated they were working on a new version, but I couldn't find it so still using this old one. IMO deprecated warning should be removed.

- **Source code**: bundled with mod in `Source` folder

Note that CSL Music Mod music packs almost always bundle their source with the mod.

### **Other Information**
- **Required mods/DLC**: missing, or listed ones are not needed. Specificy which one.

Requires CSL Music mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2474585115

Might also be worth noting that at least one of the songs in the mod contains profanity ("Girlfriend" by Avril Lavigne).

**Comment by Finwickle** [comment]
I missed that the new version wasn't released. I'll remove Deprecated, add SourceBundled and change it to Stable. The required mod is already included in the catalog.

> Might also be worth noting that at least one of the songs in the mod contains profanity ("Girlfriend" by Avril Lavigne).

I consider this to be out-of-scope for my mod. It's more something for the mod description page, or the comments.

This will be updated in catalog 3.48.
