### ISSUE TITLE
[Mod Info] Cross The Line [Steam ID  498386331] by BloodyPenguin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#14]
### **Mod:**
Cross The Line [Steam ID  498386331] by BloodyPenguin

### **Stability:**
- **Minor issues**:
    - Doesn't support constructing buildings that consume water outside of 25 tiles area.

### **Statuses:**

- **Source code**: available at https://github.com/bloodypenguin/Skylines-BuildAnywhere

### **Other Information**

- **Required mods**:

Compat report currently states:

```
 - This mod requires other mods you don't have, or which are not enabled:
    * [Steam ID  463845891] NoPillars ( v1.1+ compatible )
      Workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=463845891
```

That's... kinda complicated. The issue is that zoning won't work outside central 25 tile area. So BP mentioned the need for No Pillars mod (which is ancient and superceded by several newer mods) as it allows user to disable zoning on the roads - the user would still need to remember to do that, however.

So the real dependency there is either "any mod that allows you to disable zoning while placing roads + user actually needs to remember to do that but only for tiles outside central 25 tile area" (eg. Zoning Adjuster mods, etc) or "any mod that allows zoning to work outside central 25 tile area" (eg. 81 Tiles or equivalent).

IMO it would be best to remove the "No Pillars" requirement (as simply having that mod doesn't solve the problem unless user manually turns off zoning when building outside 25 tile area) and instead have a note about the issue, for example:

> Roads outside the central 25 tile area must have zoning disabled, unless you use 81 Tiles mod (or equivalent) which allows zoning to work on all tiles.

Also, to be fully effective, user will likely need any mod which allows camera to move outside the purchased tile border (No Border Limit Camera mod is listed by BP, but any mod with that ability will suffice). Without such a mod, the user will find it difficult to build stuff that's far outside the border because they won't be able to get good camera angle.

- **Alternatives**: which mods are alternatives for this one.

There isn't a direct alternative, but any mod that extends purchasable tile area (25 tile / 81 tile) will allow users to build in those tiles purchased outside the central 9-tile area. There are gazillions of 25 tile mods and even quite a lot of 81 tile mods (mostly outdated translations though) - a list of some I reviewed can be found here: https://github.com/CitiesSkylinesMods/AutoRepair/blob/master/AutoRepair/AutoRepair/Catalogs/Catalog.Unlimiters.cs

- **Additional info**: anything else you want to tell.

To create additional outside connections, the Unlimited Outside Connections mod is required, often with Any Road Outside Connection (depending on what roads users want to use).

**Comment by Finwickle** [comment]
Thanks for the extensive info here. This will be added to catalog 3.50.
