### ISSUE TITLE
[Mod Info] Prop Anarchy 0.6.3 [Steam ID 2696146766] by Quistar

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#15]
### **Mod:**
Prop Anarchy 0.6.3 [Steam ID 2696146766] by Quistar

and also the beta version: 2611824446

### **Statuses:**
- **Breaks editors**: NOT

Recent versions are now compatible with asset/map editors.

### **Other Information**
- **Additional info**: anything else you want to tell.

Incompatible with:

* [Undo It](https://steamcommunity.com/sharedfiles/filedetails/?id=1890830956) - incompatible according to Quistar, likely because it doesn't check size of prop array

**Comment by Finwickle** [comment]
Thanks, I'll remove the status from both versions of Prop Anarchy, and both versions of EML. I will add a note explaining that if you use it in the map editor, the created map will require Prop Anarchy.
Undo It compatibility has been dealt with in issue #35.
This will be updated in catalog 3.48.
