### ISSUE TITLE
[Mod Info] PropRotating Params [Steam ID  954067599] by Ronyx69

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#16]
### **Mod:**
PropRotating Params [Steam ID  954067599] by Ronyx69

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Deprecated**: users are discouraged to use this any longer; it won't be supported or updated.
    - Only required for old assets that used prop rotating params rather than the more modern shader approach
- **Abandoned**: no longer updated and the author doesn't respond to user questions/issues.
- **Dependency mod**: needed for some _**assets**_ but adds no functionality to the game by itself.
    - Not a hard dependency; without the mod the rotating part simply won't rotate but the asset will still be usable in-game
- **Source code**: available at:
    - Mod: https://gist.github.com/ronyx69/d892fc146019a417ae1aa3cc9b8254aa
    - Mod tools script (asset editors): https://gist.github.com/ronyx69/55f2201f2d1f2d8f6c81042c7a47e47d and https://gist.github.com/ronyx69/595c837a3141eb9c894168e385727217

### **Other Information**
- **Additional info**: anything else you want to tell.

Asset creators should use the PropRotating shader instead: https://cslmodding.info/shader/proprotating/

For advanced animations, use Custom Animation Loader: https://cslmodding.info/mod/custom-animation-loader/

**Comment by Finwickle** [comment]
This will be updated in catalog 3.50.
