### ISSUE TITLE
[Mod Info] Relight [Steam ID 1209581656] by Ronyx69

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#17]
### **Mod:**
Relight [Steam ID 1209581656] by Ronyx69

### **Stability:**
- **Minor issues**: it functions, but with some smaller issues (please elaborate below).

Compat report states:

```
 - Users are reporting issues: 
    * Light settings of Ultimate Eyecandy resetting or the light getting very dark on any 
      change in Relight settings, or at game loading. 
```

This is likely due to other external factors, notably:

* **Cubemap Replacer** mod - cubemap affects the Rayleigh scattering, so darker/cloudy cubemap will result in darker city.
* **Real Time** mod - has option to dynamically change sunset/sunrise times (based on lat/long, biome, etc); however the Relight mod has hard-coded values for those times (based on vanilla which is usually static) so it's color lerps will be out of sync with the sun position (eg. it might think it's twilight when the city is actually in morning/afternoon time)
* **Theme Mixer 2** mod - color settings of sun/moon/etc can affect the light cast on to the city, most noticably at night time (you can experiment with this effect using the sliders in Relight mod; for example, see how the two moon colours will be cast depending on the moon tint slider)

### **Statuses:**
- **Source code**: available at https://gist.github.com/ronyx69/a75400389e7561164bacabadf0095a2b

**Comment by Finwickle** [comment]
This will be updated in catalog 3.55.
