### ISSUE TITLE
[Mod Info] More Network Stuff [Steam ID  512314255] by BloodyPenguin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#18]
### **Mod:**
More Network Stuff [Steam ID  512314255] by BloodyPenguin

### **Other Information**
- **Additional info**: anything else you want to tell.

Bulldozing train and ship outside connections in-game might give errors, but if you save (under new file name), exit to desktop, then load that new save it should work fine. (I've done this many, many times over the years).

Editing aircraft paths - either adding, moving, or bulldozing - can cause the Aircraft AI to fail completely, preventing airplanes from spawning. Always save a backup of the city before altering aircraft paths.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.50.
