### ISSUE TITLE
[Mod Compatibility] Real Time vs. Transit Vehicle Spawn Delay

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#20]
Information about compatibility between two mods.

### **First mod**
Real Time [Steam ID 1420955187] by dymanoid

### **Other mod**
[Steam ID 2654110611] Transit Vehicle Spawn Delay 1.2

### **Additional information**

Apparently this issue only occurs when changing settings from the main manue; it works fine while in-game. From the [TVSD mod workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=2654110611):

> If you're using the Real Time mod, **when in-game (but not in the loading screen)** the sliders will show the correct time delay in Real Time rates.

Although default Real Time settings can be set from main menu, each game has it's own settings stored in the save, so the only reliable way to see the times in TVSD mod is to configure it in-game.

**Comment by Finwickle** [comment]
This info was partially available, but I'll add some clarification to the next catalog.
