### ISSUE TITLE
[Mod Info] Unlimited Outside Connections [Steam ID  497033453] by BloodyPenguin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#21]
### **Mod:**
Unlimited Outside Connections [Steam ID  497033453] by BloodyPenguin

### **Other Information**
- **Additional info**: anything else you want to tell.

There are issues with creating road and rail outside connections; for best results, at the outside connection use a short segment of vanilla highway, or a few segments of vanilla station train track, then connect whatever your desired road/track is to those.

Also, intercity buses (Sunset Harbor DLC) enter by a 'virtual lane' on outside highway connections. If you're not using a vanilla highway at the outside connection, or if you use 2-way network, intercity buses can/will stop working. https://github.com/CitiesSkylinesMods/TMPE/issues/960

Also, some features have been removed since original verison - would be useful to have some notes in the compat report:

> Update: 28 Feb, 2017 @ 6:29am   
> Removed: This mod **no longer adds outside connections to roads that didn't have them originally (ex: zoned roads)**. Those outside connections didn't survive save game reloading anyway. It was a mistake on my part that I added such feature in UPDATE 4. If some of NEP roads don't have outside connections please ask its author to add connections to those roads in his mod.

Zoned roads, and also roads without special 'outside connection flag', will not work as outside connections. See also: [Any Road Outside Connection](https://steamcommunity.com/sharedfiles/filedetails/?id=883332136) - apparently zoning is still an issue even with that mod.

> Update: 2 Dec, 2016 @ 8:40pm  
> Removed: Built-in camera unlimiting. Use a separate mod for that.

So a separate mod is required for allowing camera to bypass the purchased tile border limits.

**Comment by Finwickle** [comment]
I've added this already to a previous catalog, but forgot to close this.
