### ISSUE TITLE
[Mod Compatibility] Real Time vs. Cubemap Replacer

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#22]
Information about compatibility between two mods.

### **First mod**
Real Time [Steam ID 1420955187] by dymanoid

### **Other mod**
Cubemap Replacer (Read description!) [Steam ID 1183931915] by BloodyPenguin

### **Compatibility**
- **Issues** - using both mods together gives minor/major issues (please describe below).

Real Time mod can dynamically adjust the sunset/sunrise time. Cubemap Replacer uses hard-coded times for sunset/sunrise so it sometimes still shows day cubemap during night, or vanilla night sky during dawn/morning.

### **Additional information**
For best compatibility turn off Real Time's option for dynamic day lengths.

**Comment by Finwickle** [comment]
This will be added to the next catalog.
