### ISSUE TITLE
[Mod Info] Fog Controller [Steam ID 2483920668] by 네인 | neinnew

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#23]
### **Mod:**
Fog Controller [Steam ID 2483920668] by 네인 | neinnew

### **Stability:**
Choose which applies (pick only one):
- **Stable**: it simply functions fine.

### **Statuses:**

- **Source code**: available at https://github.com/neinnew/FogController

### **Other Information**

- **Additional info**: anything else you want to tell.

Recent update has obliterated the fps lag caused by earlier verisons. :)

**Comment by Finwickle** [comment]
This will be updated in catalog 3.50.
