### ISSUE TITLE
[Mod Info] Intercity Bus Control [Steam ID 2499771767] by BloodyPenguin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#24]
### **Mod:**
Intercity Bus Control [Steam ID 2499771767] by BloodyPenguin

### **Stability:**

- **Stable**: it simply functions fine.

### **Other Information**

- **Additional info**: anything else you want to tell.

Intercity buses only enter the city via 1-way highway outside connections. To make 2-way outside connections usable for intercity buses, use two 1-way highways for the outside connection then merge them in to your 2-way road.

Note: `Any Road Outside Connection` mod does _not_ fix the issue mentioned above.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.50.
