### ISSUE TITLE
[Mod Info] Network detective (for debuggin mods) [Steam ID 2152013104] by kian.zarrin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#26]
### **Mod:**
Network detective (for debuggin mods) [Steam ID 2152013104] by kian.zarrin

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Modders mod**: this is intended for modders, regular users don't need it.
- **Source code**: available at https://github.com/kianzarrin/NetworkDetective

**Comment by Finwickle** [comment]
This was already in the catalog.
