### ISSUE TITLE
[Mod Info] Sunless Radio - CSL Music Mod [Steam ID 1551413082] by Nine

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#29]
### **Mod:**
Sunless Radio - CSL Music Mod [Steam ID 1551413082] by Nine

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Source code**: bundled with mod in `Source` folder.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
