### ISSUE TITLE
[Mod Info] 0xyl0n sound mods (and sound mods in general)

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#3]
### **Mod:**

This relates to [all 0xyl0n sound mods listed in workshop](https://steamcommunity.com/profiles/76561198236123044/myworkshopfiles?browsefilter=myfiles&sortmethod=creationorder&section=items&appid=255710&requiredtags%5B%5D=Mod)

Additionally, notes below on source code apply to all sound mods in general.

### **Stability:**

- **Stable**: it simply functions fine.

### **Statuses:**

- **Source code**: bundled with mod

The 'source code' for _all_ Ambient Sounds Tuner / Vehicle Effects / Extra Vehicle Effects sound packs is included with the mod that's downloaded from workshop:

* There will be a `Source` folder inside the mod folder - in most cases it's just defining the name/description of the mod so that it can be enabled in content manager, sometimes a bit of extra code to trigger the parent mod to import the sounds
    * The code is essentially always the same; just a copy/paste based on the requirements of the parent audio mod
* Additionally there are `.xml` files with the definitions, eg. `SoundEffects.xml`, `VehicleEffectsDefinition.xml` etc.

- **Abandoned**: they aren't (but compatibility report says they are)

The 0xyl0n sound mods aren't abandoned & author is still active - eg. `Vehicle Effects Definition Pack DBAG` (id: 2008325200) was updated September 2021, and author still responsive in comments sections. Sound definition mods rarely if ever need updates as their parent mods (Ambient Sounds Tuner / Extra Vehicle Effects / etc) are rarely updated.

(The only abandoned sound mods I'm aware of are those which were designed for Ambient Sounds Tuner 1.x and never updated for AST 2.x. For example there's a UK sound mod for AST 1.x, although someone else uploaded an AST 2.x version of it)

### **Other Information**

- **Additional info**: anything else you want to tell.

The various European sound packs (for Ambient Sounds Tuner mod) have some reused audios which, if multiple Europe sounds mods are subscribed, causes `Ambient Sounds Tuner` to show warnings like this:

![image](https://user-images.githubusercontent.com/1386719/147839134-e0d27d0c-d031-4d82-8724-a039f7ab905c.png)

Those warnings are harmless; it just means duplicate audios won't be listed multiple times. Might be worth adding a note to that effect.

**Comment by Finwickle** [comment]
First of all, thanks for your extensive information on this and the other 33 issues. 👍 

I'll take a look at all of them in the coming days and report back here.

**Comment by Finwickle** [comment]
Abandoned does indeed not really apply to these kind of mods. I'll remove it from these.

This will all be updated in catalog 3.48. The abandoned status will be removed from other, similar mods in one of the catalogs after that.
