### ISSUE TITLE
[Mod Info] Toggle It! [Steam ID 1764637396] by Keallu

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#30]
### **Mod:**
Toggle It! [Steam ID 1764637396] by Keallu

### **Stability:**
- **Minor issues**: it functions, but with some smaller issues (please elaborate below).

Entering first person camera (using any mod) will cause previously hidden dashed border lines to reappear; just retoggle to hide them again.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.49.
