### ISSUE TITLE
[Mod Info] UK Sound Pack -- Updated 2.0 [Steam ID  899063611] by alborzka

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#31]
### **Mod:**
UK Sound Pack -- Updated 2.0 [Steam ID  899063611] by alborzka

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Source code**: bundled with mod in `Source` folder

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
