### ISSUE TITLE
[Mod Info] Vault Archives Music Pack [Steam ID 1289991722] by Adjex

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#32]
### **Mod:**
Vault Archives Music Pack [Steam ID 1289991722] by Adjex

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Source code**: bundled with mod in `Source` folder

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
