### ISSUE TITLE
[Mod Info] Zone radio [Steam ID 1568910950] by Zahav

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#33]
### **Mod:**
Zone radio [Steam ID 1568910950] by Zahav

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Source code**: not available.

It's using same code format as other CSL Music mods, I checked the `.dll` in ILSpy.

### **Other Information**
- **Additional info**: anything else you want to tell.

Language: Russian

**Comment by Finwickle** [comment]
Do you see the Russian language anywhere in game? Will it be confusing for non-Russians? (Never used a music mod myself)

**Comment by aubergine10** [comment]
Quite a lot of mods are translated to Russian, including TMPE, Move It, etc.

The spoken language in the Zone radio is in Russian, and the mod workshop page also states that.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
