### ISSUE TITLE
[Mod Compatibility] Real Time vs. Natural Disasters Overhaul

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#34]
Information about compatibility between two mods.

### **First mod**
Natural Disasters Overhaul [Steam ID 1801953480] by Zenya

### **Other mod**
Real Time [Steam ID 1420955187] by dymanoid

### **Compatibility**
- **Issues** - using both mods together gives minor issues (please describe below).

Natural Diasters Overhaul (NDO) is designed for use with vanilla game and gets confused by the altered flow of time caused by Real Time mod. Most notably forest fires will be much more common because NDO thinks there have been long periods without rain; set the fire probability low as a workaround.

**Comment by Finwickle** [comment]
This will be added to the next catalog.
