### ISSUE TITLE
[Mod Compatibility] Undo It vs. Extended Managers Library

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#35]
Information about compatibility between two mods.

### **First mod**
Undo It - https://steamcommunity.com/sharedfiles/filedetails/?id=1890830956

### **Other mod**
Extended Managers Library - https://steamcommunity.com/sharedfiles/filedetails/?id=2696146165

### **Compatibility**
- **Issues** - using both mods together gives minor issues (please describe below).

Undo-It was just updated to make it semi-compatible with EML / Prop Anarchy mods: https://steamcommunity.com/sharedfiles/filedetails/changelog/1890830956

If EML is enabled, Undo-It now disables it's prop-undo features so as not to cause major problems.

As such, the compatibility issue can be reduced to minor; users can now have both mods subscribed and active without breaking their props.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
