### ISSUE TITLE
[Mod Info] 81 Tiles - Intercity buses don't work outside 25 tile area

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#38]
### **Mod:**
[81 Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=576327847) by BP, and all variants

> Quistar is working on a complete new 81 Tiles implementation and is aware of the issue so hopefully that will solve the problem at some point in the future.

### **Stability:**
- **Minor issues**: it functions, but with some smaller issues (please elaborate below).

Cims won't board intercity buses at stops outside the central 25 tile area.

### **Other Information**
- **Additional info**: anything else you want to tell.

See comments on this workshop asset for more details: https://steamcommunity.com/sharedfiles/filedetails/?id=2049510825

Related TMPE guide: https://github.com/CitiesSkylinesMods/TMPE/wiki/Intercity-buses-not-working

**Comment by Finwickle** [comment]
This will be updated in the next catalog.

**Comment by aubergine10** [comment]
Quistar's version (in Extended Managers Library beta version) apparently fixes that issue (all the other older 81 Tiles mods are still affected).
