### ISSUE TITLE
[Mod Info] Adaptive Prop Visibility Distance [Steam ID  625608461]

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#4]
### **Mod:**

Adaptive Prop Visibility Distance [Steam ID  625608461]

### **Stability:**

Compatibility report states:

>  - Unsubscribe would be wise. This has `major issues`:
>    * This can have a serious impact on performance (FPS drops).

I'm not sure this should be considered major issue; the entire purpose of the mod is to increase graphics quality and users will generally recognise that doing so will put strain on their GPU.

Also, I'm not sure ULOD would resolve the fps issues; it applies blanket adjustments based on asset type, regardless of their size IIRC. With APV mod, it's adjusting the view distance setting of props based on their size, so smaller props will still disappear sooner (ULOD makes no such distinction).

As such I think it would be better to just remind users that APV / ULOD mods can impair framerate due to higher GPU strain, rather than treat it as a `major issue`.

**Comment by Finwickle** [comment]
You're right, this was a bit harsh for a graphic mod. I'll change it to Stable, still with the note about performance impact, and remove the ULOD note.
This will be updated in catalog 3.48.
