### ISSUE TITLE
FYI: Inspection of KND(KamineNoDespawn)

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#40]
As the mod workshop page doesn't provide much info I decided to take a look at the source in ILSpy.

https://steamcommunity.com/sharedfiles/filedetails/?id=2700260375

### Functionality

* **Vanilla game**: When cims are waiting for PT, the game is occasionally increasing their 'wait counter' (colloquially referred to as "boredom") - if they get too bored, they abandon the journey.
* **KamineNoDespawn**: Upon activation (via keyboard shortcut) the mod starts resetting the wait counter to `0` every `Update()`.
    * To do that it iterates all citizens, checks if their wait counter is non-zero, and, if so, sets it to zero.

> It's essentially a super-basic alternative to **Klyte45**'s [Anxiety Reducer](https://steamcommunity.com/sharedfiles/filedetails/?id=1766839841).

As far as I can tell, the purpose of KND is to help player observe which stops are most utilised without running in to vanilla issue of cims leaving due to boredom (which in turn makes the stop look less busy). In that respect the mod is unique and useful in its own right.

### Notable issues

Although **KamineNoDespawn** is simple, it has a few issues:

* Shortcut keys are hard-coded
* Iterating all cims every `Update` will cause lag on big cities that have lots of cims using PT
    * _Unlike Klyte's mod which patches the game logic that sets the wait timer = practically no additional overhead_
* While active, cims will be trapped at any broken/deleted stops (because their wait timer never increases so game won't do additional checks)
    * KamineNoDespawn mod description does mention that problem (hence the keyboard shortcut to deactivate the mod in-game)
    * _Klyte's mod limits it's 'reduction factor' to 99.25% to prevent such issues._

Suggested guidance:

* While active, may cause cims to get stuck at broken or deleted stops.
* Users with big cities or lots of PT should switch to Klyte45's [Anxiety Reducer](https://steamcommunity.com/sharedfiles/filedetails/?id=1766839841) mod to avoid in-game lag.

### KamineNoDespawn vs. Anxiety Reducer

**KamineNoDespawn** and **Anxiety Reducer** mods are _technically_ compatible (they touch different parts of code), but they are conceptually incompatible (while KND is active, it locks wait counters at zero).

Suggested guidance: 

* Users should choose one, and unsubscribe the other.

### Above mods vs. Stops & Stations

Both **KamineNoDespawn** and **Anxiety Reducer** mods are compatible with dymanoid's [Stops & Stations](https://steamcommunity.com/sharedfiles/filedetails/?id=1776052533). S&S patches game logic to prevent cims attending overcrowded stops, it doesn't affect wait timer.

**Comment by Finwickle** [comment]
Thanks for the extensive information. I'll add this to catalog 3.55.
