### ISSUE TITLE
[Mod Compatibility] `Hide It` vs. `No Radioactive Desert And More!`

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#41]
Apologies if this info already tracked, but posting here just in case.

### **First mod**
[Hide It!](https://steamcommunity.com/sharedfiles/filedetails/?id=1591417160) by Keallu

I've not checked [Hide It, Bobby!](https://steamcommunity.com/sharedfiles/filedetails/?id=2513657277) version; it's implemented slightly different so may or may not be affected by the mod below.

### **Other mod**
[No Radioactive Desert And More](https://steamcommunity.com/sharedfiles/filedetails/?id=666425898) by BP

### **Compatibility**
- **Same Functionality** - the mods provide the same functionality / change the same thing, making them incompatible.
- **Issues** - using both mods together gives major issues (please describe below).

Wen using the mods together;

> Causes all resource textures to disappear from map (user can't see where resources are in the info views)

Suggestion: Use one of the mods, not both.

### **Additional information**
https://github.com/keallu/CSL-HideIt/issues/15

**Comment by Finwickle** [comment]
The report will already warn that these mods have the same functionality and are incompatible.

**Comment by Finwickle** [comment]
And no worries about posting something that is already there. I'm really grateful for all your help.
