### ISSUE TITLE
Keallu is back and updating/fixing mods

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#42]
[List of Keallu's mods](https://steamcommunity.com/profiles/76561198050123811/myworkshopfiles/?appid=255710)

Many of them have been updated today with bug fixes and they are being transitioned to Harmony 2.x where applicable.

Abandonment flag will need removing from the mods listed above.

**Comment by aubergine10** [comment]
* Show It: https://steamcommunity.com/sharedfiles/filedetails/changelog/1556715327
* Achieve It; https://steamcommunity.com/sharedfiles/filedetails/changelog/1567569285
* Bulldoze It: https://steamcommunity.com/sharedfiles/filedetails/changelog/1627986403
* Rebuilt It: https://steamcommunity.com/sharedfiles/filedetails/changelog/1656549865

**Comment by Finwickle** [comment]
Thanks for letting me know. Keallu came to my workshop page as well. This will be updated in catalog 3.49.
