### ISSUE TITLE
[Mod Compatibility] Traffic++ V2 (2 new uploads yesterday)

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#43]
Information about compatibility between two mods.

### **First mod**
Traffic++ V2

A steam user has uploaded 2 versions of very old traffic mod made several years ago (I used to collab with jaofarias / jfarias who developed the mod) - will almost certainly break the game and many other mods: https://steamcommunity.com/profiles/76561198079266398/myworkshopfiles/?appid=255710

Steam IDs in case they get deleted:

* 2719881998
* 2719881745

Chances of T++ being updated to work with current versions of the game are practically nil without a complete rewrite.

### **Other mod**

All versions of TM:PE

### **Compatibility**
- **Same Functionality** - the mods provide the same functionality / change the same thing, making them incompatible.
- **Incompatible** - the mods are incompatible; they shouldn't be used together.
- **Successor** - the first mod is a successor of the other mod.

Use TM:PE instead. T++ was merged in to TM:PE; search `TPP2` in TM:PE changelog as it details the history: https://github.com/CitiesSkylinesMods/TMPE/blob/master/CHANGELOG.md

**Comment by Finwickle** [comment]
Thanks. I also saw them. I've added both mods as "game breaking" to yesterdays catalog with TM:PE stable as successor and a "re-upload" status.
