### ISSUE TITLE
[Mod Compatibility] `Control It!` vs. `Less Steam`

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#44]
Information about compatibility between two mods.

### **First mod**
[Control It!](https://steamcommunity.com/sharedfiles/filedetails/?id=2723628116) by Keallu

### **Other mod**
[Less Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=812107110) by thale5

### **Compatibility**
- **Same Functionality** - the mods provide the same functionality / change the same thing, making them incompatible.
- **Incompatible** - the mods are incompatible; they shouldn't be used together.

### **Additional information**

`Control It` uses `Harmony 2.x` mod by boformer so it is slightly better for overall mod compatibility / management.

However, `Control It` overlaps (maybe conflicts?) with `Hide It, Bobby!` mod (will make separate issue for that) so probably best not to treat it as a successor to `Less Steam` just yet.

**Comment by Finwickle** [comment]
This will be added to catalog 3.55. I will add `Control It` as alternative (not successor) to `Less Steam`.
