### ISSUE TITLE
[Mod Compatibility] `Control It!` vs. `Hide It, Bobby!`

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#45]
> Note: I haven't had time to test, just flagging this up as it will need testing, if someone has time...

### **First mod**
[Control It!](https://steamcommunity.com/sharedfiles/filedetails/?id=2723628116) by Keallu

### **Other mod**
[Hide It, Bobby!](https://steamcommunity.com/sharedfiles/filedetails/?id=2513657277) by User

### **Compatibility**

Both mods have options to hide panels on main menu screen, and thus will potentially conflict or cause weird issues.

- **Same Functionality** - the mods provide the same functionality / change the same thing, making them incompatible.
- **Same Functionality, but compatible** - the mods provide the same functionality, but are still compatible.

- **Specific Settings** - using both mods together requires specific settings for one or both mods (please describe below).

Based on how the mods work, so long as the user only hides/alters panels via one of the mods, they should potentially be compatible. No idea what happens if both mods try to update the same panels.

**Comment by Finwickle** [comment]
I've asked Keallu about compatibility and will await their answer.

**Comment by Finwickle** [comment]
This will be updated in catalog 4.60.
