### ISSUE TITLE
[Mod Info] `T`

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#46]
### **Mod:**
https://steamcommunity.com/sharedfiles/filedetails/?id=2726260557 by  Holy Water

### **Stability:**
- **Stable**: it simply functions fine (becuase it does nothing).

### **Statuses:**
- **Source code**: not available.

### **Other Information**
- **Additional info**: anything else you want to tell.

It does nothing at all - this is sum total of code when decompiled in ILSpy:

![image](https://user-images.githubusercontent.com/1386719/150528646-214ab60d-a1d8-43da-a581-bf64dfa7227a.png)

**Comment by Finwickle** [comment]
Thanks for the info. I assume it is a placeholder for some test mod or something. But maybe my assumption is too positive. I'll note it as NotEnoughInformation in the next catalog, since I don't trust it won't suddenly change into something non-stable.
