### ISSUE TITLE
[Mod Info] `自动取钱` (translation of AutoMoney mod)

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#47]
### **Mod:**
- https://steamcommunity.com/sharedfiles/filedetails/?id=2724629128

### **Stability:**
- **Stable**: it simply functions fine.

### **Statuses:**
- **Reupload**: it's translated (`zh-cn`) version of `AutoMoney` mod
    -  https://steamcommunity.com/sharedfiles/filedetails/?id=2036484892
- **Source code**: not available.

### **Other Information**
- **Alternatives**:
    - Original `AutoMoney` mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2036484892
- **Additional info**: anything else you want to tell.
    * Any compatibility info applicable to original `AutoMoney` mod will apply to `自动取钱` mod

**Comment by Finwickle** [comment]
This will be added to catalog 3.55.
