### ISSUE TITLE
[BUG] Possible mistake in Catalog 3.50 update

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#48]
### **Describe the bug:**

`Zone It!` mod has this flag set:

```
<ExclusionForGameVersion>true</ExclusionForGameVersion>
```

I've not checked C.Rep source code but I assume that field is to prevent warnings about "game version not specified" endlessly occuring for mods that are no longer in workshop (or are abandoned?) - if so, should it not be `false` for Zone It mod?

**Comment by Finwickle** [comment]
The <ExclusionForGameVersion> is an internal tag for the Updater process of Compatibility Report. The Updater detects the gameversion tag on the Workshop that is added by the "Improved Mod Upload Panel" mod and automatically adds and updates it to the catalog. 

The exclusion tag is to differentiate between automatically found game versions and manually set ones, so a manually set one is not overwritten by the Updater.
