### ISSUE TITLE
"Same functionality" feature can be confusing

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#49]
I'm using: Version 0.7.2.403 with catalog 3.51.

Even though there's a footnote about not needing Cross the Line, the `Unsubscribe ...` text is confusing as it makes it sound like both mods do same thing. Maybe need a way to say "Mod A includes the functionality of Mod B, but not vice versa"?

```diff
81 Tiles (Fixed for 1.2+) [Steam ID  576327847] by BloodyPenguin

- - Unsubscribe either this one or the following mod with the same functionality:
    * [Steam ID  498386331] Cross The Line
      Workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=498386331
+      With 81 tiles you don't need Cross The Line.
```

**Comment by Finwickle** [comment]
I don't want the compatibilities between two mods to be "hierarchical", but want them to be "mirrorable" (is that a word): If the compatibility is true for A towards B, it should also be true for B towards A. This to prevent overcomplicating things.

But I agree that "same functionality" is confusing/misleading sometimes. I'll change the line to:
> \- Unsubscribe either this or the following incompatible mod with similar functionality:
