### ISSUE TITLE
[Mod Info] AnimUV Params [Steam ID  940299505] by Ronyx69

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#5]
### **Mod:**
AnimUV Params [Steam ID  940299505] by Ronyx69

### **Other Information**

- **Additional info**: anything else you want to tell.

IMO it would be worth linking to the cslmodding.info pages so users and asset creators can see from the report where to get more details about the mod/shader: https://cslmodding.info/shader/animuv/

**Comment by aubergine10** [comment]
Oh, forgot to mention the mod source (and related asset editor script) can be found at:

* Mod: https://gist.github.com/ronyx69/c11629a4bd96c9bba13348e0fad7e763
* Mod Tools script (for asset creators): https://gist.github.com/ronyx69/558a2adbe7557da62ea7a7153b86e74c

You can find source/scripts for most other Ronyx69 stuff in his gists: https://gist.github.com/ronyx69

**Comment by Finwickle** [comment]
> IMO it would be worth linking to the cslmodding.info pages so users and asset creators can see from the report where to get more details about the mod/shader: https://cslmodding.info/shader/animuv/

That URL is already prominently in the very short mod description on the Workshop. If people don't read that, they'll probably also won't read the Compatibility Report. Also, the mod is, as I read it on the Workshop description, sort of deprecated for asset creators.

> Oh, forgot to mention the mod source (and related asset editor script) can be found at:

The catalog already has the source URL for AnimUV. The report doesn't display source URLs yet, but I intend to make that optional somewhere in the future.

> You can find source/scripts for most other Ronyx69 stuff in his gists: https://gist.github.com/ronyx69

I've checked and had a lot of those already in the catalog. I'll add them for five more. Thanks for the info.
