### ISSUE TITLE
[Mod Info] CSUR Loader

### ISSUE THREAD

**Issue by Monniasza** [Finwickle/CompatibilityReport#51]
Information about missing or incorrect information in the current catalog about a mod, in relation to the current game version (but unrelated to other mods; use another form for mod compatibility). You only need to included info that is now missing or incorrect. Add 'NOT' anywhere if you want current info removed.

### **Mod:**
[CSUR Loader](https://steamcommunity.com/sharedfiles/filedetails/?id=1959183067&searchtext=CSUR)

### **Stability:**
- **Broken**: it doesn't function anymore.

### **Other Information**
- **Alternatives**: [Node Controller Renewal](https://steamcommunity.com/sharedfiles/filedetails/?id=2472062376&searchtext=node+controller) and [Intersection Marking Tool](https://steamcommunity.com/sharedfiles/filedetails/?id=2140418403&searchtext=intersection+marking+tool)

**Comment by Finwickle** [comment]
This will be updated in catalog 3.59 or 4.59.
