### ISSUE TITLE
[Mod Compatibility] TM:PE STABLE/TEST compatibility changes

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#52]
### TM:PE TEST 11.6.5.0:

> https://steamcommunity.com/sharedfiles/filedetails/?id=2489276785

* **Compatible:** Reversible Tram AI
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2740907672
    * Fully compatible (sway provided some code to fix remaining issues)
* **Compatible:** Supply Chain Coloring (workshop version only)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2325122732
* **Compatible:** Transfer Broker BETA (workshop version only)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2389228470
* **Incompatible:** TM:PE LABS - discontinued (replaced by TM:PE TEST)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=1806963141
* **Incompatible:** Traffic Manager (Curated) - incompatible clone
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2749420751
* **Incompatible:** TMPE:TrafficManager全部汉化 - incompatible clone
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2263694803

### TM:PE STABLE 11.6.4.8:

> https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252

* **Minor Issues:** Reversible Tram AI
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2740907672
    * Some TM:PE customisations can't be applied to reversible tracks
* **Compatible:** Supply Chain Coloring (workshop version only)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2325122732
* **Compatible:** Transfer Broker BETA (workshop version only)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2389228470
* **Incompatible:** TM:PE LABS - discontinued (replaced by TM:PE TEST)
    * https://steamcommunity.com/sharedfiles/filedetails/?id=1806963141
* **Incompatible:** Traffic Manager (Curated) - incompatible clone
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2749420751
* **Incompatible:** TMPE:TrafficManager全部汉化 - incompatible clone
    * https://steamcommunity.com/sharedfiles/filedetails/?id=2263694803

Two of those mods are by Chaos but do not contain any malicious code and are locked from further updates, hence we are treating them as compatible (workshop versions only).

FYI: TM:PE changelogs from now on will always prefix mod compatibility changes with `[Mod]` - that will appear in the in-game `what's new` panel, and also our CHANGELOG, README, milestones, and version release PRs.

**Comment by Finwickle** [comment]
This will be updated in catalog 4.64.
