### ISSUE TITLE
[Mod Info] Building Spawn Points 1.2.3 [Steam ID 2511258910] by macsergey

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#6]
### **Mod:**
Building Spawn Points 1.2.3 [Steam ID 2511258910] by macsergey

### **Other Information**
- **Alternatives**: which mods are alternatives for this one.

```
Unsubscribe either this one or the following mod with the same functionality:
    * [Steam ID  820157360] Spawn Points Fix
      Workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=820157360
```

Is this correct? It's my understanding that `Building Spawn Points` will use default positions if a spawn point is not defined, but I don't think it adds missing spawn points (where applicable) for each station track or aircraft stop.

It would need clarifying with the mod authors, I'm just flagging here as - from what I currently know - Spawn Points Fix is still useful even if user has Building Spawn Points mod.

- **Additional info**: anything else you want to tell.

Some 'invisible vehicle spawn' assets are not compatible with Building Spawn Points (as far as I can tell; I've had no response from macsergey): https://github.com/MacSergey/BuildingSpawnPoints/issues/28

**Comment by Finwickle** [comment]
This was deducted from the Workshop description of Building Spawn Points:
> **What’s Included:** 
> * Change position of existing spawn points
> * **Add additional spawn points**

It's still quite different than **automatic** creation of spawn points for multi-track stations and I agree it can be quite useful to have both of them. I'll remove the "same functionality" compatibility. This will be updated in catalog 3.50.

The incompatible assets is not something to include in this mod, I think.
