### ISSUE TITLE
[Mod Info] All cinematic camera mods by PhatR

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#7]
### **Mod:**

All cinematic cam mods by PhatR [listed here](https://steamcommunity.com/id/ThereIsNoElectron/myworkshopfiles?browsefilter=myfiles&sortmethod=creationorder&section=items&appid=255710&requiredtags%5B%5D=Cinematic+Cameras)

### **Statuses:**
- **Source code**: bundled with mod

Each of those mods has a `Source` folder containing a single `.cs` file that defines the camera script.

**Comment by Finwickle** [comment]
This will be updated in catalog 3.48.
