### ISSUE TITLE
[Mod Info] Decal Hover Area [Steam ID  793346248] by Ronyx69

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#8]
### **Mod:**
Decal Hover Area [Steam ID  793346248] by Ronyx69

### **Stability:**
- **Stable**: it simply functions fine.

Compat report currently states:

```
 - There is not enough information about this mod to know if it works well.
    * There are hardly any comments on the Workshop over the last few years.
```

While it's true there aren't many comments, the mod does work fine - it changes the size of the hover/select circle for decals based on their size to make it easier to work with them when using mods such as Move It. It's a somewhat niche mod, used mostly by detailers.

Original announcement is on reddit with image showing what it does: https://www.reddit.com/r/CitiesSkylines/comments/5b4ym1/decal_hover_area_mod_useful_when_big_decals_get/

It became less useful when Move It (and several other mods) added a feature to skip over assets when making selections, but even so it still saves some time when doing lots of detailing with decals.

**Comment by Finwickle** [comment]
Thanks. I just couldn't find any confirmation that this still worked. I'll change it to Stable. This will be updated in catalog 3.48.
