### ISSUE TITLE
[Mod Info] Dynamic Resolution (Fixed for 1.9!) [Steam ID  812713438] by Gradius Twin

### ISSUE THREAD

**Issue by aubergine10** [Finwickle/CompatibilityReport#9]
### **Mod:**
Dynamic Resolution (Fixed for 1.9!) [Steam ID  812713438] by Gradius Twin

### **Other Information**
- **Alternatives**: which mods are alternatives for this one.

Compat report currently states:

```
 - An alternative you could use:
    * [Steam ID 1794015399] Render It!
      Workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=1794015399
```

I'm not sure that's a valid replacement as `Render It` doesn't allow user to set bigger render size, it only allows them to tweak how the current scene is rendered.

`Dynamic Resolution` mod doesn't tweak how the scene is rendered, it just changes the size of the rendering - so by default the city is rendered at screen size. DR mod allows user to render it from 25% up to something like 500% of their screen size, then scale the result back to their screen size.

Users on potato computers can get performance boost by using lower resolution than their screen size, at the expense of worse graphics quality (more blurry). For screenshots or for users with big GPUs, graphics quality can be significantly improved by rendering at higher resolutions, at the expese of more GPU load.

It might be worth noting that CSL has a special `Shift+F12` hotkey which takes a high-definition screenshot; it temporarily sets render size to 200%, takes screenshot, and saves lossless copy to folder as described here: 

![image](https://user-images.githubusercontent.com/1386719/147840560-ce6ba92e-6bc4-4455-9a20-ad2436d99e30.png)

If user only wants Dynamic Resolution mod for high-res screenshots, the Shift+F12 combo might be more suitable for their needs (as it won't be frying their GPU during normal gameplay if they forget to revert to 100% render size).

**Comment by Finwickle** [comment]
I'll add a note about Shift-F12 and remove Render It as alternative. This will be updated in catalog 3.48.
